# -*- coding: utf-8 -*-
"""Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12c4hysV0O3Z0avnrKCMIAPs0RlEBvK4w
"""

n=input("Enter n:")
s=n[::-1]
if n==s:
  print("It is a pallindrome")
else:
  print("Not a pallindrome")

n=int(input())
fact=1
for i in range(1,n+1):
  fact=fact*i
print(fact)

x=int(input())
y=int(input())
z=int(input())
if x>y and x>z:
  print(f"{x} is greater")
elif y>z:
  print(f"{y} is greater")
else:
  print(f"{z} is greater")

n=int(input())
s=str(n)
l=len(s)
total=0
for digit in s:
  total=total+int(digit)**l
if n==total:
  print(f"{n} is an armstrong number")
else:
  print(f"{n} is not an armstrong number")

a=input()
b=input()
if sorted(a)==sorted(b):
  print("anagram")
else:
  print("not an anagaram")

for num in range(1,50):
  if num<=1:
    continue
  for i in range(2,num):
    if num%i==0:
        break
  else:
    print(num)

a=10
b=5
a,b=b,a
print(a,b)



F=float(input())
C=5/9*(F-32)
print(C)

C=float(input())
F=5/9*C+32
print(F)

a="1.2"
b=map(lambda x:x*2,a.split("."))
print(list(b))

a=0
b=1
n=5
print(a)
print(b)
for i in range(n):
  c=a+b
  a=b
  b=c
  print(c)

a=int(input())
b=int(input())
c=int(input())
print((a+b+c)/3)

from functools import reduce
a=[1,2,3,4]
l=len(a)
s=reduce(lambda x,y:x+y,a)
print(s/l)

n=5
for i in range(n):
  for s in range(i):
    print(" ",end=' ')
  for j in range(n-i):
    print("*",end=' ')
  print()

n=5
for i in range(n):

  for j in range(n-i):
    print("*",end=' ')
  print()

n=4
for i in range(n):
  for s in range(i):
    print(" ",end='  ')
  for j in range(n-i-1):
    print("*",end='  ')

  for j in range(n-i):
    print("*",end='  ')
  print()



n=5
for i in range(n):
  for s in range(n-i-1):
    print(" ",end=' ')
  for j in range(i+1):
    print("*",end=' ')
  print()

n=5
for i in range(n):
  for s in range(n-i-1):
    print(" ",end=' ')
  for j in range(i+1):
    print("*",end=' ')
  print()

n=5
for i in range(n):

  for j in range(i+1):
    print(" ","*",end=' ')
  print()



s=input()
l=['a','e','i','o','u']
count=0
for ch in s:
  if ch.lower() in l or ch.upper() in l:
    count+=1
    print(ch)
print(count)

n=4
for i in range(n):
  for s in range(n-i-1):
    print(" ",end=' ')
  for j in range(i):
    print("*",end=' ')
  for j in range(i+1):
    print("*",end=' ')

  print()

n=3
for i in range(n-1):
  for s in range(n-i-1):
    print(" ",end='   ')
  for j in range(i):
    print("*",end='   ')
  for j in range(i+1):
    print("*",end='   ')

  print()
m=3
for i in range(m):
  for s in range(i):
    print(" ",end='   ')
  for j in range(m-i-1):
    print("*",end='   ')

  for j in range(m-i):
    print("*",end='   ')
  print()

a=[3,17,2,9,7,65,92]
print(max(a))
print(min(a))

a=int(input())
b=int(input())
c=int(input("Enter any option 1/2/3: "))
match c:
  case 1:
    print(a+b)
  case 2:
    print(a-b)
  case 3:
    print(a*b)
  case _:
    print("Invalid option")

n = 4

for i in range(n):

    for s in range(n-i-1):
        print(" ", end=' ')

    for j in range(i+1):
        print("*", end='   ')

    print()

s1 = "listen"
s2 = "silent"

count = 0

if len(s1) == len(s2):

    for i in range(len(s1)):

        for j in range(len(s2)):

            if s1[i] == s2[j]:
                count += 1
                break

    if count == len(s1):
        print("anagram")

    else:
        print("not an anagram")

else:
    print("not an anagram")

b=int(input())
n=int(input())
if(pow(2,b)==n):
  print("power of 2")
else:
  print("not a power of 2")

s="abcabcbb"
l=[]
for i in range(len(s)):
  sub=s[0:i+1]
  l.append(sub)
for j in l:
  if(len(j)==len(set(j))):
    l1=[]
    a=len(j)
    l1.append(a)
print(max(l1))

s1 = input()

s2 = s1[::-1]

list1 = []
list2 = []

for i in range(len(s1)):
    for j in range(i + 1, len(s1) + 1):
        sub1 = s1[i:j]
        list1.append(sub1)
for i in range(len(s2)):
    for j in range(i + 1, len(s2) + 1):
        sub2 = s2[i:j]
        list2.append(sub2)

a = set(list1)
b = set(list2)

common = a.intersection(b)
print(common)

ans = ""

for x in common:

    if x == x[::-1]:

        if len(x) > len(ans):
            ans = x

print(ans)

s1 = input()
s2 = input()
c = 0
for i in range(len(s1)):
    if s1[i] != s2[i]:
        c += 1
        print("Yes")

print(c)

s=input()

s1=s.lower()

l=['a','e','i','o','u']

v=[]
c=[]

for i in range(len(s1)):

    if s1[i] in l:
        v.append(s1[i])

    else:
        c.append(s1[i])

v = v[::-1]

ans = ""

m = min(len(v), len(c))

for i in range(m-1):

    ans += v[i]
    ans += c[i]

ans += v[-2]
ans += v[-1]
ans += c[-1]

print(ans)



n=int(input())
x=list(map(int,input().split()))
for i in range(1,n+1):
  d=x[i]
  if(x[i]==0):
    d=x[i-1]+1
    print(d)
    break

class Student:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def display(self):
    print(self.name, self.age)
obj=Student("Emman",12)
obj.display()

class Teacher:
  def func1(self):
    print("Teacher")
class Student(Teacher):
  def func2(self):
    print("Student")
obj=Student()
obj.func1()
obj.func2()

class Teacher:
  def func1(self):
    print("Teacher")
class Student(Teacher):
  def func2(self):
    print("Student")
class Parent(Student):
  def func3(self):
    print("Class C")
obj=Parent()
obj.func1()
obj.func2()
obj.func3()

class Base1:
  def func1(self):
    print("Teacher")
class Base2:
  def func2(self):
    print("Student")
class Child(Base1,Base2):
  def func3(self):
    print("Class C")
obj=Child()
obj.func1()
obj.func2()
obj.func3()

n = int(input())

l = list(map(int, input().split()))

for i in range(len(l)):

    if l[i] == -2:

        print(l[i+1] + 1)
        break

for i in range(1,6):
  if i==3:
    pass
  print(i)

n = int(input())
s=str(n)
s1=s[::-1]
n1=int(s1)

c = 0

for i in range(2, n):

    if n % i == 0 and n1%i==0:
      c += 1

if c == 0 and n > 1 and n1>1:
    print(f"{n} and {n1} are Prime")
else:
    print("Not Prime")

n=10
for i in range(1,n+1):
  if(i%2==0):
    a=-i
  else:
    a=i
  print(a)

n=int(input())
a=n*n
s=str(a)
rev=s[::-1]
n1=int(rev) #n1
print(n1)
s1=str(n)
rev1=s1[::-1]
n2=int(rev1)
b=n2*n2
print(b)
if(n1==b):
  print("Adam number")

s=input()
a=s
b=s[1:]+s[0]
c=s[-1]+s[0]+s[1]
d=int(a)
e=int(b)
f=int(c)
c1=0
c2=0
c3=0
for i in range(2,d):
  if d%i==0:
    c1+=1
for i in range(2,e):
  if e%i==0:
    c2+=1
for i in range(2,f):
  if f%i==0:
    c3+=1
if c1==0 and c2==0 and c3==0:
  print("All are prime numbers")